### ISSUE TITLE
Problem with .ini file

### ISSUE THREAD

**Issue by A-Wiedemann** [NikolausDemmel/tvseg#2]
Hello @NikolausDemmel,

for my master's thesis under supervision of Caner I am working with your code.

When I try to run the code, the output is

terminate called after throwing an instance of 'boost::exception_detail::clone_implboost::exception_detail::error_info_injector<boost::regex_error >'
what():  Found a closing ) with no corresponding openening parenthesis.  The error occurred while parsing the regular expression fragment: 'color(..*>>>HERE>>>)'.
The program has unexpectedly finished.

I am using linux. Compilation was done with a version of the .pro file from Caner.

Do you know where the error occurs?

Thanks in advance,
Andreas Wiedemann

**Comment by NikolausDemmel** [comment]
Hi,

I haven't worked in this code in a while. It looks like the regex comes from the settings parsing:

https://github.com/NikolausDemmel/tvseg/blob/23274296ea4a8fd27c08ec1e8a71ea6823b6655b/lib/tvseg/settingsdef/inputsettings.h#L15

which is later passed to `replaceString`

https://github.com/NikolausDemmel/tvseg/blob/23274296ea4a8fd27c08ec1e8a71ea6823b6655b/lib/tvseg/segmentationimpl.cpp#L93

Not sure why this regexp cannot be parsed by boost.Regex. Maybe you can have a look at the boost documentation to figure out what is going wrong. Not that apparently in 2015 I pushed a change to that regex in this commit: https://github.com/NikolausDemmel/tvseg/commit/1a8223145afcbca7b9d0c616a9ae2b4c6d053c63, but I'm not sure why. Maybe that gives a hint and you can try adding the `\\` again.

It would probably be easiest if you could upload the exact code and project file you are using. Maybe you can create a fork on github and add a new branch with the updated .pro file? Also, what is your exact configuration (Linux distro and version, compiler version, qt version, boost version, ...)?

**Comment by A-Wiedemann** [comment]
Thanks for your response.

Finally it is working. In fact the error occured in `replaceString`. In the version which Caner gave me all the settings of `tvseg.ini` are overwritten in `inputsettings.h`, where a false `colorMatch` string was set. That's why boost threw an exception.

**Comment by NikolausDemmel** [comment]
Great. Feel free to ask further questions if there are issues with the code. Sorry in advance for the lack of good documentation...
